### ISSUE TITLE
Did he get it right?

### ISSUE THREAD

**Issue by aronmek** [modhash/wedding-invite#1]
![image](https://user-images.githubusercontent.com/764151/225766111-d31c20a2-c56a-4ecd-8dc8-2f2e554befad.png)

**Comment by modhash** [comment]
No no no very wrong.

**Comment by modhash** [comment]
It feels like he never even looked at the code 
He's just going off of the domain and the repo name

**Comment by aronmek** [comment]
Got it, to my opinion though for chasidishe people like us, I think you should change the background image.

**Comment by aronmek** [comment]
I'm removing the star then. Sorry!

**Comment by modhash** [comment]
Okay I'm going to develop. A kosher version for you.

I really need that star back!

**Comment by modhash** [comment]
@aronmek fixed with commit 0c7b09a

**Comment by aronmek** [comment]
Thanks you so much
